import {readFile,writeFile} from 'node:fs/promises';
const bodies={
'projects/helmet-hud.html':`<h2>Overview</h2><p>A Raspberry Pi helmet HUD with live sensor readings, navigation, weather, and destinations sent from a phone. There are native and browser-based display options, plus a simulator for working without the hardware connected.</p><h2>Data freshness</h2><p>The sensors report at different rates. Orientation changes quickly; weather and battery readings generally do not. The display needs to distinguish a current reading from an old one, and keep the fast inputs responsive.</p><p>Sensor and phone data goes into a shared store, which supplies the display. Keeping those parts separate means I can work on the renderer or routing without needing every sensor running at once.</p><h2>Status</h2><p>Still in progress. The project includes the sensor integration, display, navigation, and phone client.</p><div class="article-actions"><a href="mailto:jerryxguo2006@gmail.com?subject=Helmet%20HUD">Contact</a></div>`,
'projects/eliza.html':`<h2>Overview</h2><p>Eliza v2 is a personal AI agent. The current version is text-based, with persistent conversations, resumable analysis, and tools. Local inference is the default, with the model provider kept replaceable.</p><h2>What persists</h2><p>A conversation can continue after a restart. Longer analysis jobs keep their status and save their results. Sessions, recorded events, and explicit tool permissions are the foundation; voice and the broader distributed runtime come later.</p><h2>The earlier version</h2><p>The original Eliza was my AI capstone project. It used separate text and audio clients connected to a generation server. That code is public, although it is an earlier implementation rather than the current v2.</p><div class="article-actions"><a href="https://github.com/ConcaveTriangle/Eliza-Legacy">Earlier version on GitHub ↗</a><a href="mailto:jerryxguo2006@gmail.com?subject=Eliza%20v2">Contact</a></div>`,
'projects/selfportrait.html':`<h2>Overview</h2><p>SelfPortrait explores generating replies in a personal conversational style. I'm working on v2; the public repository covers the earlier version.</p><h2>The earlier implementation</h2><p>The pipeline processes conversation examples, builds a training dataset, fine-tunes a model, and runs a local inference server. A client puts a suggested reply in the text box for review before sending.</p><p>Even the preprocessing involves choices: where to split a conversation, when consecutive messages count as one turn, and which examples are useful for training. These choices affect the result before the model sees any data.</p><div class="article-actions"><a href="https://github.com/ConcaveTriangle/SelfPortraitPublic">Earlier version on GitHub ↗</a><a href="mailto:jerryxguo2006@gmail.com?subject=SelfPortrait%20v2">Contact</a></div>`,
'projects/aegis.html':`<h2>Overview</h2><p>Aegis is a Reddit feed and comment filter implemented as a browser userscript. It uses local rules, with optional semantic classification through a local proxy.</p><h2>Preferences and classification</h2><p>The tool separates what a post contains from whether I want to see it. Something can be informative and still be on a topic I'd rather skip. A negative report is not automatically low quality, either.</p><p>Settings control whether matching posts are shown, flagged, or collapsed. Corrections can be recorded when the classification gets something wrong. Local rules work without a server.</p><h2>Status</h2><p>An active prototype. There isn't a public installation link yet.</p><div class="article-actions"><a href="mailto:jerryxguo2006@gmail.com?subject=Aegis">Contact</a></div>`,
'projects/spike-countdown.html':`<h2>Overview</h2><p>A small Windows overlay that displays a configurable spike countdown. It can start from visual detection of the planted-spike icon or a manual hotkey.</p><h2>Detection</h2><p>Automatic mode samples a small region near the top of the monitor. It checks red coverage, the icon's shape, and whether the normal round clock is still visible. A short confirmation period helps reject transient effects; the countdown is backdated to the first matching frame.</p><p>Manual mode captures no screen pixels. The application uses the Python standard library, does not read game memory, and does not automate gameplay.</p><h2>Limitations</h2><p>The calibrated layouts cover selected 16:9 resolutions. HUD changes may require retuning. Starting halfway through a plant cannot recover the elapsed time from the icon alone, so the overlay is a convenience rather than an authoritative clock.</p><div class="article-actions"><a href="https://github.com/ConcaveTriangle/Valorant-Spike-Countdown">Source and setup ↗</a></div><p class="source-note">An unofficial project, unaffiliated with Riot Games. Details and validation results are in the <a href="https://github.com/ConcaveTriangle/Valorant-Spike-Countdown/blob/main/README.md">README</a>.</p>`
};
for(const [path,body] of Object.entries(bodies)){
 const source=await readFile(path,'utf8');
 await writeFile(path,source.replace(/<div class="article-body">[\s\S]*?<\/div><\/article>/,`<div class="article-body">${body}</div></article>`));
}
console.log('Updated five project descriptions with shorter, direct copy.');
